---
root: true
rules:
  no-use-before-define:
    - 2
  max-len:
    - 2
    - 140
env:
  es6: true
  browser: true
  commonjs: true
  node: true
extends:
  - eslint:recommended
  - prettier
parserOptions:
  sourceType: module
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
