name: Audit

on: [push, pull_request]

jobs:
  audit:
    name: Auditing
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Source
        id: checkout-source
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm ci
      - run: npm audit
