name: Docker

on:
  push:
    branches: [ main ]

jobs:
  docker:
    name: Dockerizing
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Install jq
        run: sudo apt-get --yes install jq
      - name: Set variables
        id: vars
        run: |
          echo "::set-output name=package_name::$(cat package.json | jq -r '.name')"
          echo "::set-output name=package_version::$(cat package.json | jq -r '.version')"
      - run: |
          echo "${{steps.vars.outputs.package_name}}"
          echo "${{steps.vars.outputs.package_version}}"
      - name: Build the Docker image
        run: |
          docker build \
          --tag $DOCKER_REGISTRY/f4bio/${{steps.vars.outputs.package_name}}:${{steps.vars.outputs.package_version}} \
          --tag $DOCKER_REGISTRY/f4bio/${{steps.vars.outputs.package_name}}:latest \
          --file Dockerfile .
      - name: Authentication
        env:
          DOCKER_USERNAME: ${{github.actor}}
          DOCKER_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_TOKEN" "$DOCKER_REGISTRY"
      - name: Push Image
        run: |
          docker push $DOCKER_REGISTRY/f4bio/${{steps.vars.outputs.package_name}}:${{steps.vars.outputs.package_version}}
          docker push $DOCKER_REGISTRY/f4bio/${{steps.vars.outputs.package_name}}:latest
