name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  package_name: "landingpage"
  package_version: "2.0.1"

jobs:
  release:
    name: Releasing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: $package_version
          name: $package_name
          body: $package_name - $package_version
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: f4bio/landingpage
